name: gd_sphere
description: "Sphere is a highly customizable 3D globe widget written using a custom RenderObject.
It positions child widgets on a virtual sphere using Fibonacci distribution and renders them with depth-based scaling, alpha, and hit-testing.

This widget works on all Flutter platforms, including web, mobile, and desktop."
version: 1.0.0
homepage: https://github.com/godwinjk/flutter_sphere
repository: https://github.com/godwinjk/flutter_sphere
issue_tracker: https://github.com/godwinjk/flutter_sphere/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
